🤌
agserrano3/test_repo pull request #703
Opened 2024-01-11 15:23 UTC by agserrano3

2024-01-11 15:31 UTC, agserrano3 commented on README.md
>  this should be
i am a comment

2024-01-11 15:41 UTC, agserrano3 commented on README.md
>  this should be
i am comment #2

2024-01-12 12:17 UTC, agserrano3 commented on README.md
>  yetanothercommit
i am a fancy comment

2024-01-12 13:58 UTC, agserrano3 commented on README.md
>  yetanothercommit
another fancy comment
with multiple lines
```
code
```
and emojis: ‎

2024-01-12 14:11 UTC, codegen-team submitted a review, later dismissed
i am requesting changes

2024-01-12 14:33 UTC, agserrano3 commented on README.md
>  yetanothercommit
comment1

2024-01-12 14:33 UTC, agserrano3 commented on README.md
>  this should be
comment2

2024-01-12 14:49 UTC, codegen-team requested changes

2024-01-12 14:49 UTC, codegen-team commented on README.md
comment from another account

2024-01-15 12:25 UTC, agserrano3 commented on README.md
>  yetanothercommit
great!

2024-01-15 12:32 UTC, agserrano3 commented on README.md
>  yetanothercommit
great

2024-01-15 12:35 UTC, agserrano3 commented on README.md
>  yetanothercommit
great!

2024-01-15 12:37 UTC, agserrano3 commented on README.md
>  this should be
this should be in upper case

2024-01-15 13:02 UTC, agserrano3 commented on README.md
>  this should be
this should be in upper case

2024-01-15 13:03 UTC, agserrano3 commented on README.md
>  yetanothercommit
great

2024-01-15 13:44 UTC, agserrano3 commented on README.md
>  yetanothercommit
nice!!

2024-01-15 13:44 UTC, agserrano3 commented on README.md
>  this should be
this line should be removed

2024-01-15 13:51 UTC, codegen-team requested changes
everything is wrong

2024-01-19 17:59 UTC, agserrano3 commented on README.md
>  yetanothercommit
i am a single comment

2024-01-19 18:10 UTC, agserrano3 commented on README.md
>  yetanothercommit
1 comment in review

2024-01-19 18:11 UTC, agserrano3 reviewed
body of the review

2024-01-19 18:11 UTC, agserrano3 commented on README.md
>  yetanothercommit
1 comment in review

2024-01-19 18:14 UTC, agserrano3 commented on README.md
>  this should be
i am just a comment out of the review

2024-01-19 18:18 UTC, agserrano3 commented on README.md
>  yetanothercommit
soy una respuesta

2024-01-19 18:18 UTC, agserrano3 reviewed
algo

2024-01-23 11:26 UTC, closed without merging